# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/mmrxia"
  weibo: "http://weibo.com/u/1984883035"
  twitter: "https://twitter.com/xiaqingsong"
  linkedin: "http://www.linkedin.com/in/mrxia"
  #mail: "this.xqs@gmail.com"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: "UA-76943829-1"
favicon: "http://7xth8v.com2.z0.glb.clouddn.com/icon/favicon.ico"

#你的头像url
avatar: "http://7xth8v.com2.z0.glb.qiniucdn.com/image/avatar_150x150.jpg"
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "mrxia"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: true
#开启——
friends:
  XQS: "http://www.xiaqingsong.com"
  MORG: "http://www.morg.cn"
  Addy的网络日志: "http://www.iamaddy.net/"
  勾三股四: "http://jiongks.name/"

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: '夏青松，2013年毕业于江西农大软件学院软件工程专业。<br/>
<b>2012.10-2015.2</b> [北京] 锐捷网络<br/>
<b>2015.2-至今</b> [杭州] 妈妈好网络<br/><br/>
Mail：this.xqs@gmail.com
'
